### ISSUE TITLE
Choose between erase and reset or only reset board

### ISSUE THREAD

**Issue by fooons** [G4lile0/ESP32-OLED-Fossa-GroundStation#14]
If board is operated in Remote Desktop or not accessible by the user to push buttons, a good **enhancement** could be a question when "e" erase is selected in the menu and allow to "erase and reset" or only "reset" the board.

**Comment by 4m1g0** [comment]
Thanks for the suggestion!!

Just to be sure, now 'e' works as "erase and reset", right? Adding an option to just reset would be enough.

**Comment by fooons** [comment]
Sure, thanks
