### ISSUE TITLE
getFrequencyError is not implemented for sx1268

### ISSUE THREAD

**Issue by lillefyr** [G4lile0/ESP32-OLED-Fossa-GroundStation#19]
When compiling the 'groundstation.ino' for Fossasat-1 and selecting SX126x chipset, the code that successfully calls getFrequencyError for SX127x fails.

This is because getFrequencyError is not implemented for sx1268 in RadioLib.
Is there a way to get the Frequency Error on sx1268 or is it only implemented for sx1278 ?

If not implemented, please add a check for the radio type.

#ifndef RADIO_SX126X
    // print frequency error
    Serial.print(F("[SX12x8] Frequency error:\t"));
    Serial.print(lora.getFrequencyError());
    Serial.println(F(" Hz"));
#endif

**Comment by 4m1g0** [comment]
Fixed, on beta release.

Thanks!
